# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TCtrl_Tune.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 810)
        MainWindow.setMinimumSize(QtCore.QSize(10, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.TabFilterDefinition = QtWidgets.QWidget()
        self.TabFilterDefinition.setObjectName("TabFilterDefinition")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.TabFilterDefinition)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.wid_Filter1 = FilterDefinition(self.TabFilterDefinition)
        self.wid_Filter1.setObjectName("wid_Filter1")
        self.verticalLayout_3.addWidget(self.wid_Filter1)
        self.wid_Filter2 = FilterDefinition(self.TabFilterDefinition)
        self.wid_Filter2.setObjectName("wid_Filter2")
        self.verticalLayout_3.addWidget(self.wid_Filter2)
        self.wid_Filter3 = FilterDefinition(self.TabFilterDefinition)
        self.wid_Filter3.setObjectName("wid_Filter3")
        self.verticalLayout_3.addWidget(self.wid_Filter3)
        self.wid_Filter4 = FilterDefinition(self.TabFilterDefinition)
        self.wid_Filter4.setObjectName("wid_Filter4")
        self.verticalLayout_3.addWidget(self.wid_Filter4)
        self.wid_Filter5 = FilterDefinition(self.TabFilterDefinition)
        self.wid_Filter5.setObjectName("wid_Filter5")
        self.verticalLayout_3.addWidget(self.wid_Filter5)
        self.wid_Filter6 = FilterDefinition(self.TabFilterDefinition)
        self.wid_Filter6.setObjectName("wid_Filter6")
        self.verticalLayout_3.addWidget(self.wid_Filter6)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.TabFilterDefinition, "")
        self.TabPITune = QtWidgets.QWidget()
        self.TabPITune.setObjectName("TabPITune")
        self.tabWidget.addTab(self.TabPITune, "")
        self.horizontalLayout_4.addWidget(self.tabWidget)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter_4 = QtWidgets.QSplitter(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_4.sizePolicy().hasHeightForWidth())
        self.splitter_4.setSizePolicy(sizePolicy)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.frame_plot_1_1 = MyRLocusFrame(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_plot_1_1.sizePolicy().hasHeightForWidth())
        self.frame_plot_1_1.setSizePolicy(sizePolicy)
        self.frame_plot_1_1.setMinimumSize(QtCore.QSize(10, 0))
        self.frame_plot_1_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_plot_1_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_plot_1_1.setObjectName("frame_plot_1_1")
        self.frame_plot_1_2 = MyBodeFrame(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_plot_1_2.sizePolicy().hasHeightForWidth())
        self.frame_plot_1_2.setSizePolicy(sizePolicy)
        self.frame_plot_1_2.setMinimumSize(QtCore.QSize(10, 0))
        self.frame_plot_1_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_plot_1_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_plot_1_2.setLineWidth(5)
        self.frame_plot_1_2.setObjectName("frame_plot_1_2")
        self.splitter_3 = QtWidgets.QSplitter(self.splitter_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_3.sizePolicy().hasHeightForWidth())
        self.splitter_3.setSizePolicy(sizePolicy)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.frame_plot_2_1 = MyBodeFrame(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_plot_2_1.sizePolicy().hasHeightForWidth())
        self.frame_plot_2_1.setSizePolicy(sizePolicy)
        self.frame_plot_2_1.setMinimumSize(QtCore.QSize(1, 0))
        self.frame_plot_2_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_plot_2_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_plot_2_1.setObjectName("frame_plot_2_1")
        self.frame_plot_2_2 = MyBodeFrame(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_plot_2_2.sizePolicy().hasHeightForWidth())
        self.frame_plot_2_2.setSizePolicy(sizePolicy)
        self.frame_plot_2_2.setMinimumSize(QtCore.QSize(10, 0))
        self.frame_plot_2_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_plot_2_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_plot_2_2.setLineWidth(5)
        self.frame_plot_2_2.setObjectName("frame_plot_2_2")
        self.verticalLayout_2.addWidget(self.splitter_4)
        self.horizontalLayout_2.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1440, 21))
        self.menubar.setObjectName("menubar")
        self.menuMain = QtWidgets.QMenu(self.menubar)
        self.menuMain.setObjectName("menuMain")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionLoad_Model = QtWidgets.QAction(MainWindow)
        self.actionLoad_Model.setObjectName("actionLoad_Model")
        self.actionZoom = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/icons8-search-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom.setIcon(icon)
        self.actionZoom.setObjectName("actionZoom")
        self.menuMain.addAction(self.actionLoad_Model)
        self.menubar.addAction(self.menuMain.menuAction())
        self.toolBar.addAction(self.actionZoom)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabFilterDefinition), _translate("MainWindow", "Filter Definition"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabPITune), _translate("MainWindow", "PI Tune"))
        self.menuMain.setTitle(_translate("MainWindow", "Main"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionLoad_Model.setText(_translate("MainWindow", "Load Model"))
        self.actionZoom.setText(_translate("MainWindow", "Zoom"))
        self.actionZoom.setToolTip(_translate("MainWindow", "Zoom"))

from FilterDefinition import FilterDefinition
from MyWidgetClasses import MyBodeFrame, MyRLocusFrame
import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

